name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: releases
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    env:
      CC: gcc-12
      CXX: g++-12

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install meson g++-12 ninja-build

      - name: Cache subprojects
        id: meson-cache
        uses: actions/cache@v3
        with:
          path: subprojects/packagecache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Configure
        run: meson setup --buildtype release --default-library static  build-linux

      - name: Compile
        run: ninja -C build-linux

      - name: Test
        run: ninja -C build-linux test

      - name: Binary
        uses: actions/upload-artifact@v3
        with:
          name: dregarnuhr-linux
          path: build-linux/src/dregarnuhr

  build-mac:
    runs-on: macos-latest
    env:
      CC: gcc-12
      CXX: g++-12

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          brew update
          brew install meson libxml2 gcc@12 ninja

      - name: Cache subprojects
        id: meson-cache
        uses: actions/cache@v3
        with:
          path: subprojects/packagecache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Configure
        run: meson setup --buildtype release --default-library static build-mac

      - name: Compile
        run: ninja -C build-mac

      - name: Test
        run: ninja -C build-mac test

      - name: Binary
        uses: actions/upload-artifact@v3
        with:
          name: dregarnuhr-macos
          path: build-mac/src/dregarnuhr

  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install meson ninja

      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64

      - name: Cache subprojects
        id: meson-cache
        uses: actions/cache@v3
        with:
          path: subprojects/packagecache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Configure
        run: |
          meson setup --buildtype release -Dc_std=c17 -Dcpp_std=c++20 -Dcpp_eh=a --default-library static build-win

      - name: Compile
        run: ninja -C build-win

      - name: Test
        run: ninja -C build-win test

      - name: Binary
        uses: actions/upload-artifact@v3
        with:
          name: dregarnuhr-win
          path: build-win/src/dregarnuhr.exe

  release:
    needs: [build-linux, build-mac, build-win]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - id: myref
        env:
          REF: ${{ github.event.ref }}
        run: echo "::set-output name=MYREF::`echo $REF | tr -d refs/tags`"

      - run: tar -C ./dregarnuhr-linux -czvf "dregarnuhr-linux-${{ steps.myref.outputs.MYREF }}.tar.gz" dregarnuhr
      - run: tar -C ./dregarnuhr-macos -czvf "dregarnuhr-mac-${{ steps.myref.outputs.MYREF }}.tar.gz" dregarnuhr
      - run: zip -j ./dregarnuhr-win dregarnuhr-win/dregarnuhr.exe
      - run: mv ./dregarnuhr-win.zip "./dregarnuhr-windows-${{ steps.myref.outputs.MYREF }}.zip"

      - name: Release Linux Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dregarnuhr-linux-${{ steps.myref.outputs.MYREF }}.tar.gz
          asset_name: dregarnuhr-linux-${{ steps.myref.outputs.MYREF }}.tar.gz
          asset_content_type: application/gzip

      - name: Release Mac Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dregarnuhr-mac-${{ steps.myref.outputs.MYREF }}.tar.gz
          asset_name: dregarnuhr-mac-${{ steps.myref.outputs.MYREF }}.tar.gz
          asset_content_type: application/gzip

      - name: Release Windows Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dregarnuhr-windows-${{ steps.myref.outputs.MYREF }}.zip
          asset_name: dregarnuhr-windows-${{ steps.myref.outputs.MYREF }}.zip
          asset_content_type: application/zip
